# Generated by Django 4.1.1 on 2022-11-22 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseChampions',
            fields=[
                ('courseCode', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('courseName', models.CharField(max_length=30)),
                ('champion', models.CharField(max_length=60)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
