# Generated by Django 3.2.9 on 2022-12-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coursechampions_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_details',
            old_name='timetable',
            new_name='odd',
        ),
    ]
