# Generated by Django 3.2.9 on 2022-12-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_timetable_faculty_details_odd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_details',
            old_name='odd',
            new_name='timetable',
        ),
    ]
