# Generated by Django 3.2.9 on 2022-12-30 06:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_odd_faculty_details_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='even',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=9), default=[None], size=None),
            preserve_default=False,
        ),
    ]
