# Generated by Django 3.2.9 on 2023-01-09 07:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_faculty_details_even'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_details_even',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('timetable', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=9), size=None)),
            ],
        ),
    ]
