# Generated by Django 3.2.9 on 2023-01-09 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_faculty_details_even'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseChampions_even',
            fields=[
                ('courseCode', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8)])),
                ('courseName', models.CharField(max_length=100)),
                ('champion', models.CharField(max_length=60)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
